name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Inject Supabase Keys into Config JS
      run: |
        find . -name "supabase-config.js" -exec sed -i "s#__SUPABASE_URL__#${{ vars.SUPABASE_URL }}#g" {} +
        find . -name "supabase-config.js" -exec sed -i "s#__SUPABASE_ANON_KEY__#${{ vars.SUPABASE_ANON_KEY }}#g" {} +
